### ISSUE TITLE
Give clone1018 access to Motherboard

### ISSUE THREAD

**Issue by clone1018** [Dallas-Makerspace/tracker#21]
## Expected Behavior 
Cannot access motherboard.dms.local

## Actual Behavior
Can access motherboard.dms.local

**Comment by denzuko** [comment]
Your user name was added for the logistics committee and since your the committee chair we have promoted you to team leader. You should be able to add new users under your committee as needed.

![Proof](https://imgur.com/download/kuNuKoF)

Please validate and mark close if no further assistance is needed.
