### ISSUE TITLE
Add a ReadOnly active directory user? for clone1018 to use in testing

### ISSUE THREAD

**Issue by clone1018** [Dallas-Makerspace/tracker#23]
## Expected Behavior 
I'd like to do some local testing of MakerManager/Calendar, I can't seem to get a local activedirectory setup. Ideally I could use production DMS for testing instead.

**Comment by denzuko** [comment]
I can create a service account for you. However anyone that's not using their adm_* account is readonly by default.

**Comment by clone1018** [comment]
So I could authenticate right now with my personal DMS credentials? I need
access for a local instance of the calendar or maker manager . I'm not sure
if AD has api credentials or not?

**Comment by denzuko** [comment]
> authenticate right now with my personal DMS credentials?

Yes, unlike modern sql/nosql databases. AD is just a very opinionated LDAP+Kerberos+CIFS+DNS server which is a schema based nosql technology and that protocol standard by design is read only by default which is known as an anonymous bind to the server.

Broken down authentication in ldap is fairly straight forward:

  1) use an ldap query to walk the AD Forest collecting all matching objects in an OU related to Members
  2) filter for memberOf attribute in records for a matching group CN
  3) compare either commonName. uid, or samAccountName with a user provided value
  4) optionally validate a hash ticket from Kerberos or more commonly compare the userPassword attribute with user provided one

This can be seen in [LdapAuthentication.php](https://github.com/Dallas-Makerspace/makermanager/blob/ec18fe9a08886a874ab45e2bf229e43e10eb8822/src/Auth/LdapAuthenticate.php)
where lines `12:18` are just to establish the anonymous connection. 
Followed by `line 23` binding as the user with whom is authenticating thus filling out steps 3 and 4.
Then `lines 25:27` preforms step 1 with a filter for the `samAccountName` and `line 36:45` is then in this case already assuming (incorrectly) that a matched object is valid and is now comparing the group membership (e.g. step 4) to assign the session user as an admin or not.
 
While `Lines 47` and on are just extra cruft logic to cross check a table record in an sql based server.

Calendar is doing roughly the same thing in `AppController.php:46` but in this case its leveraging a cakephp plugin component to provide other controllers with an abstracted a) `$this.Auth.authenticate` and b. `$this.Auth.authroized` methods to do just that a. authenticate the user then b. check if they're authorized to preform an action.

At the end of the day both are really just binding with the authenticating user's credentials instead of running with a service account style binding then validating the user.
